0: orange_dye
1: pink_dye
2: beetroot
3: red_dye
4: yellow_dye
5: black_dye
6: bone_meal
7: cyan_dye
8: gray_dye
9: light_blue_dye
10: light_gray_dye
11: lime_dye
12: magenta_dye
13: beef
14: apple
15: arrow
16: bone
17: book
18: bowl
19: bread
20: brick
21: cake
22: carrot
23: charcoal
24: chicken
25: clay_ball
26: coal
27: cooked_beef
28: cooked_chicken
29: cooked_rabbit
30: diamond
31: egg
32: emerald
33: flint
34: glowstone_dust
35: gold_ingot
36: gold_nugget
37: golden_carrot
38: gunpowder
39: green_dye
40: iron_ingot
41: iron_nugget
42: lapis_lazuli
43: melon_slice
44: potato