0: stone
1: acacia_planks
2: gray_wool
3: bedrock
4: birch_planks
5: bricks
6: clay
7: cobblestone
8: coal_ore
9: green_wool
10: dark_prismarine
11: oak_planks
12: spruce_planks
13: dark_oak_planks
14: chiseled_stone_bricks
15: warped_planks
16: glowstone
17: iron_block
18: blue_ice
19: obsidian
20: diamond_block
21: diamond_ore
22: emerald_block
23: emerald_ore
24: end_stone
25: granite
26: gold_block
27: gold_ore
28: jungle_planks
29: lapis_block
30: lapis_ore
31: light_blue_wool
32: lime_concrete
33: lime_wool
34: orange_concrete
35: orange_wool
36: pink_concrete
37: pink_wool
38: polished_diorite
39: polished_granite
40: prismarine_bricks
41: purple_wool
42: sand
43: sponge
44: white_wool
